insert into public.portal_customer_profiles (
  id,
  status,
  loan_type,
  application_number,
  loan_number,
  apply_date,
  id_number,
  name,
  mobile,
  partaker_type,
  blacklist_flag,
  source_system,
  age,
  job,
  company_unit,
  apply_info,
  partakers,
  credit_ref,
  documents,
  mortgage,
  dsr,
  loan_history,
  partaking_history,
  approval_info,
  repay_history,
  repay_condition,
  crm,
  oca_write_off
) values
(
  'cust-001',
  'Active servicing',
  'Term loan',
  'APP-2024-8891',
  'LN-778821',
  '2024-06-12',
  'S1234567A',
  'Tan Wei Ming',
  '+65 9123 4410',
  'Primary borrower',
  false,
  'Core LOS / Unit A',
  44,
  'Director - SME',
  'Unit A',
  '{"product":"Secured term - SME working capital","branch":"Central Operations","applicationDate":"2024-06-12","status":"Disbursed - performing","applicantNote":"Repeat borrower; prior facility closed 2023 without arrears."}'::jsonb,
  '[{"name":"Tan Hui Ling","relationship":"Spouse / guarantor","contact":"+65 9123 4411","linkedId":"cust-882"},{"name":"Apex Supplies Pte Ltd","relationship":"Related corporate","contact":"finance@apex-supplies.example"}]'::jsonb,
  '{"summary":"Internal score band B+; two trade references verified Q2 2024.","indicators":["No active disputes","One settled facility 2019"]}'::jsonb,
  '[{"type":"ID / KYC","date":"2024-06-10","reference":"DOC-KYC-99102"},{"type":"Financial statements","date":"2024-06-11","reference":"DOC-FIN-44021"},{"type":"Charge / security","date":"2024-07-01","reference":"DOC-SEC-22011"}]'::jsonb,
  '{"applicable":true,"assetSummary":"Commercial unit - Lot 12-441, indexed valuation SGD 1.85M.","collateralRef":"COL-MTG-009821"}'::jsonb,
  '{"income":"SGD 42,500 / month (stated)","expenditure":"SGD 18,200 / month (underwriting)","ratio":"42.8%","notes":"DSR within policy at approval; refreshed figures scheduled Q3."}'::jsonb,
  '[{"loanNumber":"LN-551002","product":"Revolving credit","status":"Closed - fully repaid","period":"2019-01 - 2023-08"},{"loanNumber":"LN-778821","product":"Term loan","status":"Active","period":"2024-07 - present"}]'::jsonb,
  '[{"period":"2021","description":"Guarantor on related corporate facility (since closed).","relatedApplication":"APP-2021-2201"}]'::jsonb,
  '[{"stage":"Credit committee","date":"2024-06-28","reviewer":"Committee pack CC-441","decision":"Approved with standard covenants","notes":"Conditions: charge registration, insurance confirmation."},{"stage":"Operations disbursement","date":"2024-07-02","reviewer":"Ops - J. Koh","decision":"Released","notes":"All CPs satisfied."}]'::jsonb,
  '[{"date":"2024-08-01","amount":"SGD 12,400","balanceAfter":"SGD 487,200","channel":"GIRO"},{"date":"2024-09-01","amount":"SGD 12,400","balanceAfter":"SGD 474,800","channel":"GIRO"},{"date":"2024-10-01","amount":"SGD 12,400","balanceAfter":"SGD 462,400","channel":"GIRO"}]'::jsonb,
  '{"terms":"Monthly amortising, 60 months, fixed coupon tier-1","state":"Current","overdueDays":0,"collectionNotes":"No active collection queue."}'::jsonb,
  '[{"date":"2024-09-15","author":"Servicing - M. Rahim","note":"Annual review scheduled; no material changes reported."}]'::jsonb,
  '{"ocaRecords":["None on file for this borrower ID."],"writeOffRecords":["None."],"recovery":"N/A"}'::jsonb
),
(
  'cust-002',
  'Special mention',
  'Invoice financing',
  'APP-2023-4410',
  'LN-661902',
  '2023-11-02',
  'F887712C',
  'Priya Narayanan',
  '+65 9001 2210',
  'Primary borrower',
  false,
  'Legacy CRM / Unit B',
  39,
  'Owner - trading',
  'Unit B',
  '{"product":"Invoice financing - revolving","branch":"North Hub","applicationDate":"2023-11-02","status":"Restructuring discussion","applicantNote":"Cash-flow stress from anchor buyer payment delays."}'::jsonb,
  '[{"name":"Brightline Trading Pte Ltd","relationship":"Debtor / counterparty","contact":"ap@brightline.example"}]'::jsonb,
  '{"summary":"Watchlist for concentration to single buyer; external bureau stable.","indicators":["Elevated utilisation","No prior defaults"]}'::jsonb,
  '[{"type":"Assignment deed","date":"2023-11-05","reference":"DOC-ASG-11002"}]'::jsonb,
  '{"applicable":false,"assetSummary":"Unsecured structure.","collateralRef":"-"}'::jsonb,
  '{"income":"Variable - trailing 6-mo avg SGD 28,000","expenditure":"SGD 19,500","ratio":"69.6%","notes":"Under temporary forbearance metrics pending restructuring."}'::jsonb,
  '[{"loanNumber":"LN-661902","product":"Invoice financing","status":"Active - watch","period":"2023-11 - present"}]'::jsonb,
  '[]'::jsonb,
  '[{"stage":"Annual review","date":"2024-08-20","reviewer":"R. Santos","decision":"Continue with enhanced monitoring","notes":"Buyer payment behaviour to be reviewed monthly."}]'::jsonb,
  '[{"date":"2024-09-10","amount":"SGD 4,200","balanceAfter":"SGD 118,900","channel":"Bank transfer"}]'::jsonb,
  '{"terms":"Revolver - monthly interest, principal on invoice settlement","state":"1-30 DPD intermittent","overdueDays":12,"collectionNotes":"Soft calls logged; restructuring proposal in draft."}'::jsonb,
  '[{"date":"2024-10-02","author":"Collections - L. Goh","note":"Borrower responsive; awaiting revised buyer payment plan."}]'::jsonb,
  '{"ocaRecords":["Legal review not initiated."],"writeOffRecords":["None."],"recovery":"N/A"}'::jsonb
),
(
  'cust-003',
  'Written off',
  'Personal term',
  'APP-2019-2201',
  'LN-330021',
  '2019-04-18',
  'G1122334B',
  'Lee Kuan Hock',
  '+65 8777 0091',
  'Primary borrower',
  true,
  'Recovery ledger / Unit C',
  56,
  'Sales',
  'Unit C',
  '{"product":"Unsecured personal term","branch":"East","applicationDate":"2019-04-18","status":"Closed - write-off","applicantNote":"Facility written off after prolonged default; legal file active."}'::jsonb,
  '[]'::jsonb,
  '{"summary":"Historical file; bureau shows settled write-off flag.","indicators":["Blacklist - internal","External recovery firm engaged historically"]}'::jsonb,
  '[{"type":"Demand letter","date":"2020-03-01","reference":"DOC-DMD-003311"}]'::jsonb,
  '{"applicable":false,"assetSummary":"N/A","collateralRef":"-"}'::jsonb,
  '{"income":"N/A","expenditure":"N/A","ratio":"N/A","notes":"File archived; figures not maintained post write-off."}'::jsonb,
  '[{"loanNumber":"LN-330021","product":"Personal term","status":"Written off","period":"2019-05 - 2021-02"}]'::jsonb,
  '[{"period":"2018","description":"Co-borrower on withdrawn application (not disbursed).","relatedApplication":"APP-2018-9011"}]'::jsonb,
  '[{"stage":"Final write-off","date":"2021-02-14","reviewer":"Committee WO-12","decision":"Write-off approved","notes":"Recovery efforts exhausted per policy."}]'::jsonb,
  '[{"date":"2020-01-05","amount":"SGD 800","balanceAfter":"SGD 21,400","channel":"Cash deposit"}]'::jsonb,
  '{"terms":"N/A - closed","state":"Write-off","overdueDays":999,"collectionNotes":"Transferred to external counsel2021; sporadic trace activity."}'::jsonb,
  '[{"date":"2023-01-10","author":"Recovery - external","note":"Skip trace update - no new employer verified."}]'::jsonb,
  '{"ocaRecords":["OCA ref OCA-2019-7712 - demand and filing logged."],"writeOffRecords":["WO-2021-0099 - principal SGD 21,400 + accrued charges."],"recovery":"Lifetime recovery SGD 3,200; outstanding written balance carried."}'::jsonb
),
(
  'cust-004',
  'Pending approval',
  'Bridging loan',
  'APP-2025-1188',
  'LN-900114',
  '2025-01-22',
  'T5566778D',
  'Aisha Binte Rahman',
  '+65 8111 2204',
  'Primary borrower',
  false,
  'SME Intake / Unit D',
  36,
  'Operations Manager',
  'Unit D',
  '{"product":"Short-term bridging facility","branch":"South Hub","applicationDate":"2025-01-22","status":"Pending final approval","applicantNote":"Bridge requested ahead of expected receivables release next month."}'::jsonb,
  '[{"name":"Rahman Logistics Pte Ltd","relationship":"Employer / related company","contact":"ops@rahmanlogistics.example"},{"name":"Mohd Firdaus","relationship":"Guarantor","contact":"+65 8111 2205"}]'::jsonb,
  '{"summary":"Internal review acceptable; bureau clean with moderate existing leverage.","indicators":["No write-off history","One active auto loan externally"]}'::jsonb,
  '[{"type":"Payslips","date":"2025-01-20","reference":"DOC-PAY-55102"},{"type":"Bank statements","date":"2025-01-21","reference":"DOC-BNK-99120"}]'::jsonb,
  '{"applicable":false,"assetSummary":"Unsecured bridge supported by salary and receivables evidence.","collateralRef":"-"}'::jsonb,
  '{"income":"SGD 11,800 / month","expenditure":"SGD 5,100 / month","ratio":"43.2%","notes":"Within underwriting range pending employer callback completion."}'::jsonb,
  '[{"loanNumber":"LN-900114","product":"Bridging loan","status":"Application","period":"2025-01 - present"}]'::jsonb,
  '[]'::jsonb,
  '[{"stage":"Credit analyst review","date":"2025-01-24","reviewer":"N. Lim","decision":"Recommend approve","notes":"Awaiting sign-off from final approver."}]'::jsonb,
  '[]'::jsonb,
  '{"terms":"Not yet disbursed","state":"Pre-disbursement","overdueDays":0,"collectionNotes":"N/A"}'::jsonb,
  '[{"date":"2025-01-24","author":"Sales - H. Tan","note":"Customer confirmed use of funds for supplier settlement bridge."}]'::jsonb,
  '{"ocaRecords":["None."],"writeOffRecords":["None."],"recovery":"N/A"}'::jsonb
),
(
  'cust-005',
  'Active watchlist',
  'Merchant cash advance',
  'APP-2024-7711',
  'LN-882004',
  '2024-03-04',
  'H7654321K',
  'Jason Ong',
  '+65 9333 8841',
  'Primary borrower',
  false,
  'Collections CRM / Unit E',
  41,
  'Restaurant Owner',
  'Unit E',
  '{"product":"Merchant cash advance","branch":"Retail Finance Desk","applicationDate":"2024-03-04","status":"Restructured - monitored","applicantNote":"Sales softened after mall renovation works reduced foot traffic."}'::jsonb,
  '[{"name":"Ong Mei Lin","relationship":"Spouse / emergency contact","contact":"+65 9333 8842"}]'::jsonb,
  '{"summary":"Internal score deteriorated after missed deductions in Q4 2024.","indicators":["Two recent promise-to-pay arrangements","No legal escalation yet"]}'::jsonb,
  '[{"type":"Merchant statements","date":"2024-12-15","reference":"DOC-MER-77701"},{"type":"Restructure letter","date":"2025-01-08","reference":"DOC-RST-44002"}]'::jsonb,
  '{"applicable":false,"assetSummary":"Unsecured MCA structure.","collateralRef":"-"}'::jsonb,
  '{"income":"Variable - avg SGD 16,200 / month","expenditure":"SGD 10,700 / month","ratio":"66.0%","notes":"Stress case remains elevated despite revised deduction schedule."}'::jsonb,
  '[{"loanNumber":"LN-882004","product":"Merchant cash advance","status":"Active - monitored","period":"2024-03 - present"}]'::jsonb,
  '[{"period":"2022","description":"Guarantor for sibling business overdraft.","relatedApplication":"APP-2022-6670"}]'::jsonb,
  '[{"stage":"Restructure approval","date":"2025-01-06","reviewer":"Workout Desk","decision":"Approved revised deduction schedule","notes":"Weekly monitoring required for first 8 weeks."}]'::jsonb,
  '[{"date":"2025-01-15","amount":"SGD 2,100","balanceAfter":"SGD 38,400","channel":"Card settlements"},{"date":"2025-01-22","amount":"SGD 1,950","balanceAfter":"SGD 36,450","channel":"Card settlements"}]'::jsonb,
  '{"terms":"Daily card settlement sweep with temporary reduced cap","state":"Under watch","overdueDays":7,"collectionNotes":"Escalate if two more weekly sweeps miss target."}'::jsonb,
  '[{"date":"2025-01-23","author":"Collections - P. Dass","note":"Owner reported traffic improving; next review in one week."}]'::jsonb,
  '{"ocaRecords":["Soft collection queue active."],"writeOffRecords":["None."],"recovery":"N/A"}'::jsonb
),
(
  'cust-006',
  'Closed - repaid',
  'Equipment financing',
  'APP-2022-5104',
  'LN-440773',
  '2022-09-14',
  'M3344556P',
  'Ng Sok Hoon',
  '+65 8770 1432',
  'Primary borrower',
  false,
  'Asset Finance / Unit F',
  52,
  'Workshop Owner',
  'Unit F',
  '{"product":"Equipment financing - CNC machine","branch":"Industrial Lending","applicationDate":"2022-09-14","status":"Closed after full repayment","applicantNote":"Facility settled early after increase in export orders."}'::jsonb,
  '[{"name":"Sok Hoon Engineering","relationship":"Borrowing business","contact":"admin@sokhoon-eng.example"}]'::jsonb,
  '{"summary":"Strong historical repayment performance and good utilization discipline.","indicators":["No arrears history","Early settlement completed"]}'::jsonb,
  '[{"type":"Invoice for equipment","date":"2022-09-10","reference":"DOC-EQP-23019"},{"type":"Discharge letter","date":"2024-11-03","reference":"DOC-DSC-55004"}]'::jsonb,
  '{"applicable":true,"assetSummary":"First charge over financed CNC unit.","collateralRef":"COL-AF-440773"}'::jsonb,
  '{"income":"SGD 24,000 / month","expenditure":"SGD 9,800 / month","ratio":"40.8%","notes":"Historical DSR remained compliant throughout facility life."}'::jsonb,
  '[{"loanNumber":"LN-440773","product":"Equipment financing","status":"Closed - repaid","period":"2022-10 - 2024-11"}]'::jsonb,
  '[]'::jsonb,
  '[{"stage":"Initial approval","date":"2022-09-20","reviewer":"Asset Finance Committee","decision":"Approved","notes":"Standard asset charge and insurance conditions applied."}]'::jsonb,
  '[{"date":"2024-09-03","amount":"SGD 4,500","balanceAfter":"SGD 8,900","channel":"Bank transfer"},{"date":"2024-10-03","amount":"SGD 4,500","balanceAfter":"SGD 4,400","channel":"Bank transfer"},{"date":"2024-11-03","amount":"SGD 4,400","balanceAfter":"SGD 0","channel":"Bank transfer"}]'::jsonb,
  '{"terms":"Monthly instalment - facility closed","state":"Closed","overdueDays":0,"collectionNotes":"No collection actions required."}'::jsonb,
  '[{"date":"2024-11-05","author":"Servicing - C. Neo","note":"Discharge documents sent; customer thanked team and may reapply in H2."}]'::jsonb,
  '{"ocaRecords":["None."],"writeOffRecords":["None."],"recovery":"N/A"}'::jsonb
)
on conflict (id) do update set
  status = excluded.status,
  loan_type = excluded.loan_type,
  application_number = excluded.application_number,
  loan_number = excluded.loan_number,
  apply_date = excluded.apply_date,
  id_number = excluded.id_number,
  name = excluded.name,
  mobile = excluded.mobile,
  partaker_type = excluded.partaker_type,
  blacklist_flag = excluded.blacklist_flag,
  source_system = excluded.source_system,
  age = excluded.age,
  job = excluded.job,
  company_unit = excluded.company_unit,
  apply_info = excluded.apply_info,
  partakers = excluded.partakers,
  credit_ref = excluded.credit_ref,
  documents = excluded.documents,
  mortgage = excluded.mortgage,
  dsr = excluded.dsr,
  loan_history = excluded.loan_history,
  partaking_history = excluded.partaking_history,
  approval_info = excluded.approval_info,
  repay_history = excluded.repay_history,
  repay_condition = excluded.repay_condition,
  crm = excluded.crm,
  oca_write_off = excluded.oca_write_off;
